//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeDiplom
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Номер_заказа { get; set; }
        public string Имя_клиента { get; set; }
        public Nullable<int> Название_кофе { get; set; }
        public Nullable<int> Количество { get; set; }
        public Nullable<int> Обьем { get; set; }
        public string Доп_игредиенты { get; set; }
    
        public virtual Coffee Coffee { get; set; }
    }
}
